server:
  port: 8080
  servlet:
    context-path: /music
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: love